from BOT import main_call
main_call({'ACCOUNT_ID': '',
 'ACTIVE_VOLUME': 5,
 'ATR_CHECK': 0.047,
 'ATR_CHECKS': 0.047,
 'ATR_VALUE': 0.99,
 'AVG_VOLUMNS_CANDLES': 30,
 'BODY': 2.0,
 'CALL_DELTA_CHECK': 0.35,
 'CLIENTID': 0,
 'IP': '127.0.0.1',
 'MAX_CONTRACT_AMOUNT': 350,
 'MIDPOINT_OFFSET': 0.01,
 'ORDER_EXPIRY_TIMER': 15,
 'ORDER_TRANSMIT': True,
 'PORT': 7497,
 'PUT_DELTA_CHECK': -0.35,
 'QUANTITY': 2,
 'SHARE_VOLUME': 1,
 'SPY_QQQ_EXPIRY': '20230922',
 'SWITCH_DB': 0,
 'USE_DIFF_EXPIRY_INDEX': 'yes',
 'USE_TIMER_IN_ORDER': 'ON',
 'VOLUME_CHECK': 100,
 'VWAP_ON_OFF': 'ON',
 'candleTime': '1 min',
 'distance_between_trade': 300,
 'expiryToTrade': 'current',
 'fetchValue': '1 D',
 'marketStartTime': '19:00:00',
 'perDayTrades': 3,
 'profit_increment': 0.03,
 'scriptEndTime': '0935',
 'scriptStartTime': '1545',
 'stockData': {'SPY': {'amount': 350}},
 'stockListToTrade': {'SPY': 'NASDAQ'}})